---
- hosts:  all
  become: true
  tasks:  
  - name: update repository index
    ansible.builtin.dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora"
  - name: install httpd
    ansible.builtin.dnf:
      name: httpd
      state:  present
    when: ansible_distribution == "Fedora"
  - name: install support for php
    ansible.builtin.dnf:
      name: php
      state:  present
    when: ansible_distribution == "Fedora"
  
