---
- hosts: localhost
  vars:
    x: 5
  gather_facts: false
  tasks:
  - ansible.builtin.debug:
      msg:
       - "x value is: {{x}}"
  - ansible.builtin.set_fact:
      x: 33
      y: "SAT"
  - ansible.builtin.debug:
      msg:
       - "x value is: {{x}}"
       - "y value is: {{y}}"
