---
- name: Play to get java version
  hosts: all
  gather_facts: false
  tasks:
  - name: Executing java version command with command module
    ansible.builtin.command:
      cmd:  'java -version'
    register: javaVersion
  - name: Displaying java  version using debug module
    ansible.builtin.debug:
      msg: "{{(javaVersion.stderr|split)[2]|trim('\"')}}"
