---
- name: Simple if-else statement
  hosts: localhost
  vars:
    a: 30
    b: 60
  gather_facts: false
  tasks:
  - name: Find the larger 
    ansible.builtin.set_fact:
      larger: "{{ a if a>b else b}}"
  - name: Find the larger number using if else
    ansible.builtin.debug:
      msg:
      - "The larger number is: {{ larger}}"
