---
- name: Play to execute ant command
  hosts: all
  gather_facts: false
  tasks:
  - name: Executing given command
    ansible.builtin.command:
      cmd:  "{{inputCmd}}"
    register: cmdOutput
  - name: Displaying result
    ansible.builtin.debug:
      msg: "{{cmdOutput.stdout}}"
    when: cmdOutput.stdout | length != 0
  - name: Displaying result
    ansible.builtin.debug:
      msg: "{{cmdOutput.stderr}}"
    when: cmdOutput.stderr | length != 0

