---
- name: Play to install packages on different os families
  hosts: all
  gather_facts: true
  become: yes
  tasks:
  - import_tasks: var37.yml
    when: ansible_facts.os_family == "RedHat"
  - import_tasks: var38.yml
    when: ansible_facts.os_family == "Debian"
