---
- name: Play with become options
  hosts: all
  gather_facts: false
  tasks:
  - name: Install httpd package
    ansible.builtin.yum:
      name: httpd
      state: absent
    become: yes
    become_user: root
    become_method: sudo

