---
- name: Play to install httpd and then to start it
  hosts: all
  gather_facts: false
  become: yes
  tasks:
  - name: Install httpd
    ansible.builtin.dnf:
      name: httpd
      state: present
    notify: Start httpd
#    register: output
#  - name: Display the results
#    ansible.builtin.debug:
#      msg: "{{output.changed}}"
  handlers:
  - name: Start httpd
    ansible.builtin.service:
      name: httpd
      state: started
#    when: output.changed
