---
- name: Play to understand about error handling
  hosts: all
  gather_facts: false
  tasks:
  - name: Finding nginx version
    ansible.builtin.command:
      cmd: 'nginx -version'
    register: nginxVeroutput
    ignore_errors:  true
  - name: Finding uname info
    ansible.builtin.command:
      cmd: uname
    register: unameOutput
  - name: Displaying httpd versiona and uname details
    ansible.builtin.debug:
      msg:
      - "httpd version: {{nginxVeroutput.stderr}}"
      - "uname: {{unameOutput.stdout}}"
