---
- name: Play for loops
  hosts: all
  gather_facts: false
  tasks:
  - name: Creating a file
    ansible.builtin.file:
      path: /tmp/config
      state: touch
  - name: Creating a file
    ansible.builtin.file:
      path: /tmp/config.default
      state: touch
  - name: Creating a file
    ansible.builtin.file:
      path: /tmp/config.test
      state: touch

