---
- name: Play for loops
  hosts:  all
  gather_facts: false
  vars:
    reqFiles:
    - { 'name': 'config22' , 'dir': '/tmp' , 'mode': '0755' }
    - { 'name': 'config33' , 'dir': '/home/tpm' , 'mode': '0666' }
    - { 'name': 'config44' , 'dir': '/home/ansibleadmin' , 'mode': '0757' }
  tasks:
  - name: Creating a file
#    ansible.builtin.debug:
#      msg: "name={{item.name}} dir={{item.dir}}"
    ansible.builtin.file:
      path: "{{item.dir}}/{{item.name}}"
      state: touch
      mode: "{{item.mode}}"
    loop: "{{reqFiles}}"
