---
- name: Display vars
  hosts: all
  vars:
    x:  2
    y:  5.6
    myname: Tharindu
  gather_facts: false
  tasks:
  - name: Display vars
    ansible.builtin.debug:
     msg: "{{x}} {{y}} {{myname}}"
  - name: Display vars2
    ansible.builtin.debug:
     msg: "y value is: {{y}}"
  - name: Display vars3
    ansible.builtin.debug:
     msg: "{{myname}}"
